### ISSUE TITLE
Error: error loading plugins: loading plugin /data/ipfs/plugins/go-ds-s3.so: not built with cgo support

### ISSUE THREAD

**Issue by tiago-peres** [ipfs/go-ds-s3#213] opened 2021-12-17 21:31 UTC
After

1- cloning the repo
2- run `make build` (getting as output `s3plugin.so`)
3- run `make install`
4- make the appropriate changes in both `/data/ipfs/config` 

```
"Datastore": {
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "Spec": {
      "mounts": [
        {
         "child": {
           "type": "s3ds",
           "region": "us-east-1",
           "bucket": "ipfs-test2-node",
           "accessKey": "******",
           "secretKey": "******"
        },
        "mountpoint": "/blocks",
        "prefix": "s3.datastore",
        "type": "measure"
       },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
```

and `/data/ipfs/datastore_spec`, 

```
{"mounts":[{"bucket":"ipfs-test2-node","mountpoint":"/blocks","region":"us-east-1","rootDirectory":""},{"mountpoint":"/","path":"datastore","type":"levelds"}],"type":"mount"}
```

I restarted ipfs `sudo systemctl restart ipfs`

and then while checking that didn't have errors

    systemctl status ipfs

then got

> Error: error loading plugins: loading plugin /data/ipfs/plugins/go-ds-s3.so: not built with cgo support

![image](https://user-images.githubusercontent.com/13332903/146609600-6592c5ab-21f3-4db6-8aab-f8684842f501.png)

**Comment by Stebalien** [comment] 2021-12-19 23:45
Do you have `CGO_ENABLED=0` set in your environment? That'll break plugin builds.

Run `make build CGO_ENABLED=1`.

**Comment by Stebalien** [comment] 2021-12-19 23:47
Fix in https://github.com/ipfs/go-ds-s3/pull/214.

**Comment by Stebalien** [comment] 2021-12-19 23:57
Merged. Please close this issue if it works, otherwise respond here.

**Comment by tiago-peres** [comment] 2021-12-20 13:04
That didn't solve the issue for me though...

![image](https://user-images.githubusercontent.com/13332903/146771393-fd4f0aad-1adb-4f5b-a4a2-4f605ac9e5a3.png)

**Comment by Stebalien** [comment] 2021-12-20 22:57
Ah... sorry, I misinterpreted the source of the message.

The issue is that your go-ipfs version itself wasn't built with CGO support. How did you build/install go-ipfs?

**Comment by tiago-peres** [comment] 2021-12-21 12:39
I followed the next steps

1. `wget https://dist.ipfs.io/go-ipfs/v0.9.1/go-ipfs_v0.9.1_linux-386.tar.gz` (download go-ipfs binary)

2. `tar xvfz go-ipfs_v0.9.1_linux-386.tar.gz` (unpack the binary)

3. `rm go-ipfs_v0.9.1_linux-386.tar.gz` (remove the downloaded archive)

4. `sudo mv go-ipfs/ipfs /usr/local/bin` (move it to a particular folder)

5. `rm -rf go-ipfs` (remove it from the other location)

6. `echo 'export IPFS_PATH=/data/ipfs' >>~/.bash_profile` (add the IPFS repo path (/data/ipfs) to the .bash_profile script)

7. `source ~/.bash_profile (source what was done before` (run the code contained in the file))

8. `sudo mkdir -p $IPFS_PATH` (make sure to make the required directory)

9. `sudo chown ubuntu:ubuntu $IPFS_PATH` (take ownership of the directory)

10. `ipfs init --profile server` (initialize IPFS server)

**Comment by Stebalien** [comment] 2021-12-21 20:07
Ah, I see. At the moment, plugins only work on 64bit Linux for the _pre-built_ binaries (because they're built on 64bit linux and building go-ipfs with CGO support for foreign architectures is tricky). For now, you'll have to build go-ipfs from source or use the 64bit version (or use the go-ipfs docker container).

I've filed an issue to support this in our build system (https://github.com/ipfs/distributions/issues/546).

**Closed by Stebalien** 2021-12-21 20:07 UTC
Labels: need/triage

**Comment by Stebalien** [comment] 2021-12-21 20:08
(but please use the latest version, v0.9.1 is about 4 months out of date and is missing some important fixes)

**Comment by tiago-peres** [comment] 2021-12-28 21:27
@Stebalien while using an Ubuntu 20.04 (x86), if I change the first step to

    wget https://dist.ipfs.io/go-ipfs/v0.11.0/go-ipfs_v0.11.0_linux-amd64.tar.gz

like you're suggesting, then eventually when initializing the IPFS server, this is what will get

    ERROR   provider.queue  queue/queue.go:124      Failed to enqueue cid: leveldb: closed

![image](https://user-images.githubusercontent.com/13332903/147605947-8159cb66-ea57-4f43-afef-a6d035dfa587.png)

This error would also happen using `https://dist.ipfs.io/go-ipfs/v0.11.0/go-ipfs_v0.11.0_linux-386.tar.gz`, yet according to [hector](https://discuss.ipfs.io/t/error-provider-queue-failed-to-enqueue-cid-leveldb-closed/11551/2?u=tiago)

> It is superficial and has no effect on the installation.

Anyways, I followed through with the procedure with `go-ipfs_v0.11.0_linux-amd64` and in the end got into the same problem

![image](https://user-images.githubusercontent.com/13332903/147608254-2a76506e-dbbf-4f2e-a930-bcce7e0c4910.png)

**Comment by Stebalien** [comment] 2021-12-28 23:51
There should be more to that error log. Hector is right, that error is a different bug (that shouldn't actually affect anything).
